name: Twitch Bot CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted  # Runs directly on your Raspberry Pi

    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Install Dependencies (Using Local Python Installation)
      - name: Install Dependencies
        run: |
          python3.11 -m pip install --upgrade pip  # Use python3.11 if installed, or python3.10
          pip install -r requirements.txt

      # 3. Run Black Formatter Check
      - name: Run Black Formatter Check
        uses: psf/black@stable
        with:
          options: --check --diff --line-length 120 --exclude '/venv|__pycache__/'
          src: .
          summary: true

      # 4. Deploy to Raspberry Pi
      - name: Deploy to Raspberry Pi
        run: |
          REVUBOT_DIR=~/revbot
          REPO_URL=https://github.com/Revulate/revbot.git

          # Create revbot directory if it doesn't exist
          mkdir -p $REVUBOT_DIR
          cd $REVUBOT_DIR

          # If .git exists, pull; else, clone the repository
          if [ -d ".git" ]; then
            git fetch origin
            git checkout main
            git pull origin main
          else
            git clone --branch main $REPO_URL .
          fi

          # Create virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            python3.11 -m venv venv  # Use python3.11 if installed, or python3.10
          fi

          # Activate the virtual environment
          source venv/bin/activate

          # Upgrade pip within the virtual environment
          python3.11 -m pip install --upgrade pip  # Use python3.11 if installed, or python3.10

          # Install dependencies within the virtual environment
          pip install -r requirements.txt

          # Create or update the .env file
          cat <<EOF > .env
          TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }}
          ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
          EOF

          # Restart the Twitch bot service
          sudo systemctl restart twitch-bot.service
