name: Twitch Bot CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      # 1. Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # 2. Set up Python 3.10
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # 3. Install Dependencies
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run Black Formatter Check
      - name: Run Black Formatter Check
        uses: psf/black@stable
        with:
          options: --check --diff --line-length 120 --exclude '/venv|__pycache__/'
          src: .
          summary: true

      # 5. Deploy to Raspberry Pi
      - name: Deploy to Raspberry Pi
        run: |
          REVUBOT_DIR=~/revbot
          REPO_URL=https://github.com/Revulate/revbot.git  # Ensure this is your correct repository URL

          # Create revbot directory if it doesn't exist
          mkdir -p $REVUBOT_DIR
          cd $REVUBOT_DIR

          # If .git exists, pull; else, clone the repository
          if [ -d ".git" ]; then
            git fetch origin
            git checkout main
            git pull origin main
          else
            git clone --branch main $REPO_URL .
          fi

          # Create virtual environment if it doesn't exist
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi

          # Activate the virtual environment
          source venv/bin/activate

          # Upgrade pip within the virtual environment
          python -m pip install --upgrade pip

          # Install dependencies within the virtual environment
          pip install -r requirements.txt

          # Create or update the .env file
          cat <<EOF > .env
          TWITCH_CLIENT_ID=${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_CLIENT_SECRET=${{ secrets.TWITCH_CLIENT_SECRET }}
          ACCESS_TOKEN=${{ secrets.ACCESS_TOKEN }}
          EOF

          # Restart the Twitch bot service
          sudo systemctl restart twitch-bot.service
