name: Twitch Bot CI/CD Pipeline

# Trigger workflows on push or pull request to the new-rewrite branch
on:
  push:
    branches:
      - new-rewrite
  pull_request:
    branches:
      - new-rewrite
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Linting using flake8
      - name: Run Linter
        run: |
          pip install flake8
          flake8 .

      # Run unit tests using pytest
      - name: Run Tests
        run: |
          pip install pytest
          pytest --cov=.

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/new-rewrite'

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Deploy locally (Windows PC)
      - name: Deploy Locally
        run: |
          echo "Deployment step for local Windows PC - adjust this step as needed"
